on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: "Install Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: "beta,pubsub-emulator"
      - name: "Start Pub/Sub emulator"
        run: |
          gcloud beta emulators pubsub start --project=testproject --host-port=0.0.0.0:8085 &
      - name: Run program
        env:
          PUBSUB_EMULATOR_HOST: "localhost:8085"
        run: |
          go run main.go
